### ISSUE TITLE
sftp.json example

### ISSUE THREAD

**Issue by Zenoo** [CasperPas/jefftp#2]
Where could I find a `sftp.json` sample ? Where every available field is visible.

**Comment by CasperPas** [comment]
You can check it here: https://github.com/CasperPas/jefftp/blob/8831ddf845fc687bb35855521f7060e179cb8863/src/modules/config.ts#L14

or here:
https://github.com/CasperPas/jefftp/blob/8831ddf845fc687bb35855521f7060e179cb8863/src/interfaces.ts#L3
